"""create twin state tables

Revision ID: fff62028844f
Revises: 
Create Date: 2026-08-31 08:05:07.529125+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'fff62028844f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('belt_name', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_geospatial_index('idx_sites_centroid', 'sites', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_sites_geom', 'sites', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('equipment_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', name='equipment_status'), nullable=False),
    sa.Column('last_status_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_last_status_change'), 'equipment', ['last_status_change'], unique=False)
    op.create_index(op.f('ix_equipment_site_id'), 'equipment', ['site_id'], unique=False)
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('actual_output', sa.Float(), nullable=True),
    sa.Column('target_output', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', name='uq_production_records_site_date')
    )
    op.create_index(op.f('ix_production_records_date'), 'production_records', ['date'], unique=False)
    op.create_index(op.f('ix_production_records_site_id'), 'production_records', ['site_id'], unique=False)
    op.create_geospatial_table('reserve_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.Text(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('estimated_grade_pct', sa.Float(), nullable=True),
    sa.Column('estimated_depth_m', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_reserve_zones_geom', 'reserve_zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_reserve_zones_last_updated'), 'reserve_zones', ['last_updated'], unique=False)
    op.create_index(op.f('ix_reserve_zones_site_id'), 'reserve_zones', ['site_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='risk_severity'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_entity_type', sa.Text(), nullable=True),
    sa.Column('source_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_detected_at'), 'risk_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_risk_events_site_id'), 'risk_events', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_site_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_detected_at'), table_name='risk_events')
    op.drop_table('risk_events')
    sa.Enum(name='risk_severity').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_reserve_zones_site_id'), table_name='reserve_zones')
    op.drop_index(op.f('ix_reserve_zones_last_updated'), table_name='reserve_zones')
    op.drop_geospatial_index('idx_reserve_zones_geom', table_name='reserve_zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('reserve_zones')
    op.drop_index(op.f('ix_production_records_site_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_date'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_equipment_site_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_last_status_change'), table_name='equipment')
    op.drop_table('equipment')
    sa.Enum(name='equipment_status').drop(op.get_bind(), checkfirst=True)
    op.drop_geospatial_index('idx_sites_geom', table_name='sites', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_index('idx_sites_centroid', table_name='sites', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('sites')
    # ### end Alembic commands ###
