"""add blast_events table

Revision ID: ddd398038e1a
Revises: b1f3c7a9d2e4
Create Date: 2026-09-07 16:25:49.068110+00:00

Adds `blast_events` (planned vs actual blasts, with a structured delay
reason) and its two native enum types. Purely additive - no existing table
is touched.

`downgrade` drops both enum types explicitly: dropping a table does not drop
the enum types its columns referenced, and leaving them behind makes a
repeat `upgrade head` fail on "type already exists" (see
tests/test_migrations.py::test_migration_upgrade_downgrade_cycle_is_clean).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ddd398038e1a'
down_revision: Union[str, None] = 'b1f3c7a9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blast_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('reserve_zone_id', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'delayed', 'cancelled', name='blast_status'), server_default='planned', nullable=False),
    sa.Column('delay_reason', sa.Enum('permit_pending', 'weather_hold', 'safety_hold', 'equipment_unavailable', 'explosive_supply', name='blast_delay_reason'), nullable=True),
    sa.Column('expected_yield_tonnes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_yield_tonnes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reserve_zone_id'], ['reserve_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blast_events_planned_date'), 'blast_events', ['planned_date'], unique=False)
    op.create_index(op.f('ix_blast_events_reserve_zone_id'), 'blast_events', ['reserve_zone_id'], unique=False)
    op.create_index(op.f('ix_blast_events_site_id'), 'blast_events', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blast_events_site_id'), table_name='blast_events')
    op.drop_index(op.f('ix_blast_events_reserve_zone_id'), table_name='blast_events')
    op.drop_index(op.f('ix_blast_events_planned_date'), table_name='blast_events')
    op.drop_table('blast_events')
    sa.Enum(name='blast_delay_reason').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='blast_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
