"""add equipment_status_log table

Revision ID: 87b25057ff45
Revises: b3c612abd01e
Create Date: 2026-09-08 15:45:13.674819+00:00

Field Intake Hardening Phase 4 (§2.1). Purely additive: one new table, no
existing table touched. `Equipment.status` remains the single source of
truth for current status — this table is append-only history.

Clean autogenerate this time (unlike b3c612abd01e) — the dev DB has no
half-applied Phase 4 state, so the diff against a fresh DB and this dev DB
agree; no conditional-DDL workaround is needed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '87b25057ff45'
down_revision: Union[str, None] = 'b3c612abd01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), server_default='system', nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_status_log_changed_at'), 'equipment_status_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_equipment_status_log_equipment_id'), 'equipment_status_log', ['equipment_id'], unique=False)
    op.create_index('ix_equipment_status_log_equipment_id_changed_at', 'equipment_status_log', ['equipment_id', sa.literal_column('changed_at DESC')], unique=False)
    op.create_index(op.f('ix_equipment_status_log_site_id'), 'equipment_status_log', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_status_log_site_id'), table_name='equipment_status_log')
    op.drop_index('ix_equipment_status_log_equipment_id_changed_at', table_name='equipment_status_log')
    op.drop_index(op.f('ix_equipment_status_log_equipment_id'), table_name='equipment_status_log')
    op.drop_index(op.f('ix_equipment_status_log_changed_at'), table_name='equipment_status_log')
    op.drop_table('equipment_status_log')
    # ### end Alembic commands ###
