"""add shift_plan_entries table

Revision ID: db428e3b813a
Revises: ddd398038e1a
Create Date: 2026-09-08 14:08:58.296941+00:00

Adds `shift_plan_entries` — a snapshot of one `GET /recommendations` option
that a planner committed via `POST /shift-plan`. Purely additive: no
existing table, column, or type is touched, and no other route reads it.
There are no native enum types here, so `downgrade` only has to drop the
table and its two FK indexes.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'db428e3b813a'
down_revision: Union[str, None] = 'ddd398038e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_event_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('projected_impact', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_plan_entries_risk_event_id'), 'shift_plan_entries', ['risk_event_id'], unique=False)
    op.create_index(op.f('ix_shift_plan_entries_site_id'), 'shift_plan_entries', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_plan_entries_site_id'), table_name='shift_plan_entries')
    op.drop_index(op.f('ix_shift_plan_entries_risk_event_id'), table_name='shift_plan_entries')
    op.drop_table('shift_plan_entries')
    # ### end Alembic commands ###
